CREATE TABLE products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 store VARCHAR(255) NOT NULL, external_id VARCHAR(200) NOT NULL,
 name VARCHAR(1000) NOT NULL, url VARCHAR(2048) NOT NULL, image_url VARCHAR(2048),
 current_price NUMERIC(19,2), previous_price NUMERIC(19,2), original_price NUMERIC(19,2),
 lowest_price NUMERIC(19,2), highest_price NUMERIC(19,2), average_price NUMERIC(19,2),
 average30day_price NUMERIC(19,2), last_alert_price NUMERIC(19,2),
 store_discount NUMERIC(19,2), historical_discount NUMERIC(19,2),
 active BOOLEAN NOT NULL, available BOOLEAN NOT NULL, deal BOOLEAN NOT NULL,
 coupon_code VARCHAR(200), created_at TIMESTAMP WITH TIME ZONE,
 updated_at TIMESTAMP WITH TIME ZONE, last_checked_at TIMESTAMP WITH TIME ZONE, version BIGINT,
 CONSTRAINT product_identity UNIQUE(store, external_id)
);
CREATE TABLE price_history (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id),
 price NUMERIC(19,2) NOT NULL CHECK(price > 0), original_price NUMERIC(19,2),
 discount_percentage NUMERIC(19,2), coupon VARCHAR(200), available BOOLEAN NOT NULL,
 collected_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX history_product_time ON price_history(product_id, collected_at);
CREATE TABLE tracked_products (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 store VARCHAR(255) NOT NULL, url VARCHAR(2048) NOT NULL, target_price NUMERIC(19,2),
 active BOOLEAN NOT NULL, created_at TIMESTAMP WITH TIME ZONE,
 CONSTRAINT tracked_identity UNIQUE(store,url), CHECK(target_price IS NULL OR target_price > 0)
);
CREATE TABLE alerts (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id),
 alert_type VARCHAR(100) NOT NULL, price NUMERIC(19,2), discount NUMERIC(19,2), coupon_code VARCHAR(200),
 fingerprint VARCHAR(64) NOT NULL UNIQUE, status VARCHAR(20) NOT NULL, payload TEXT NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE, sent_at TIMESTAMP WITH TIME ZONE, next_attempt_at TIMESTAMP WITH TIME ZONE,
 attempts INTEGER NOT NULL, delivery_error VARCHAR(100)
);
CREATE INDEX alerts_dispatch ON alerts(status,next_attempt_at);
CREATE INDEX alerts_product_time ON alerts(product_id,created_at);
CREATE TABLE coupons (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id BIGINT NOT NULL REFERENCES products(id),
 code VARCHAR(200) NOT NULL, discount_percentage NUMERIC(19,2), discount_value NUMERIC(19,2),
 minimum_purchase NUMERIC(19,2), expires_at TIMESTAMP WITH TIME ZONE, source VARCHAR(2048),
 CONSTRAINT coupon_identity UNIQUE(product_id,code)
);

